### ISSUE TITLE
Driver sign not working

### ISSUE THREAD

**Issue by skvl** [utoni/mingw-w64-dpp#2]
Hello.

Thanks for great project!

I have tried to build self-signed driver from Your sample https://github.com/utoni/mingw-w64-driver . So I have added few lines into Makefile:
```
      install: $(DRIVER_TARGET)
            $(call INSTALL_EXEC_SIGN,$(DRIVER_TARGET))
```

Then run build with command `make DPP_ROOT=../mingw-w64-dpp/ DESTDIR=bin install`.

After that in `bin` directory files `codesign-ca-cert.crt` and `driver.sys` appeared.

I have installed certificate in system and tried to install driver with `sc.exe [create|start]`. On `start` it failed with signature error.

I have found issues https://github.com/mtrojnar/osslsigncode/issues/86 and https://github.com/mtrojnar/osslsigncode/issues/111 . So I believe that this should work.

Could You please provide some more details on the topic?

Thanks in advance!

**Comment by utoni** [comment]
The issue is that current Windows systems have a feature named DSE. This project does neither disable DSE nor does it sign the driver file with a legitimate signature. The resulting driver is self-signed. Thus you will need to disable DSE e.g. enabling test signing mode, use EfiGuard or something else to circumvent/disable DSE.

**Comment by skvl** [comment]
Thanks for reply.

Though I have enabled test signing mode with `bcdedit /set testsigning on` command.

I have build self-signed driver on Windows (a CMake based project) signed like this ( https://github.com/SnoopWare/usbsnoop/blob/master/CMakeLists.txt ). And this driver works.

**Comment by utoni** [comment]
Thanks for pointing that out. I'll try it test signing mode enabled.

**Comment by skvl** [comment]
Thanks a lot!

**Comment by utoni** [comment]
I can confirm this issue when using testsigning mode. But I am wondering why the self signed drivers are rejected by the system. Do you have any idea?

**Comment by skvl** [comment]
Hello.

Sorry for the late answer.

At the time I don't have any idea. The only thing I know for sure is that self-signed driver like this ( https://github.com/SnoopWare/usbsnoop/blob/master/CMakeLists.txt ) works. So I believe  that there is some issues with arguments to osslsigncode.

**Comment by utoni** [comment]
Sorry for the late fix. I was somewhat busy the last weeks.
It is now possible to self-sign your `mingw-w64-dpp` drivers natively on a Windows OS.

**Comment by skvl** [comment]
Thanks! I would try
